# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRecord = channel.unary_unary(
                '/myapp.DatabaseService/CreateRecord',
                request_serializer=service__pb2.CreateRequest.SerializeToString,
                response_deserializer=service__pb2.CreateResponse.FromString,
                )
        self.ReadRecord = channel.unary_unary(
                '/myapp.DatabaseService/ReadRecord',
                request_serializer=service__pb2.ReadRequest.SerializeToString,
                response_deserializer=service__pb2.ReadResponse.FromString,
                )
        self.UpdateRecord = channel.unary_unary(
                '/myapp.DatabaseService/UpdateRecord',
                request_serializer=service__pb2.UpdateRequest.SerializeToString,
                response_deserializer=service__pb2.UpdateResponse.FromString,
                )
        self.DeleteRecord = channel.unary_unary(
                '/myapp.DatabaseService/DeleteRecord',
                request_serializer=service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=service__pb2.DeleteResponse.FromString,
                )


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRecord(self, request, context):
        """Create operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRecord(self, request, context):
        """Read operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecord(self, request, context):
        """Update operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecord(self, request, context):
        """Delete operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecord,
                    request_deserializer=service__pb2.CreateRequest.FromString,
                    response_serializer=service__pb2.CreateResponse.SerializeToString,
            ),
            'ReadRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRecord,
                    request_deserializer=service__pb2.ReadRequest.FromString,
                    response_serializer=service__pb2.ReadResponse.SerializeToString,
            ),
            'UpdateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecord,
                    request_deserializer=service__pb2.UpdateRequest.FromString,
                    response_serializer=service__pb2.UpdateResponse.SerializeToString,
            ),
            'DeleteRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecord,
                    request_deserializer=service__pb2.DeleteRequest.FromString,
                    response_serializer=service__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myapp.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.DatabaseService/CreateRecord',
            service__pb2.CreateRequest.SerializeToString,
            service__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.DatabaseService/ReadRecord',
            service__pb2.ReadRequest.SerializeToString,
            service__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.DatabaseService/UpdateRecord',
            service__pb2.UpdateRequest.SerializeToString,
            service__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.DatabaseService/DeleteRecord',
            service__pb2.DeleteRequest.SerializeToString,
            service__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
