# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05myapp\"B\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"!\n\x0e\x43reateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0bReadRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"U\n\rUpdateRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\rDeleteRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x01\n\x0f\x44\x61tabaseService\x12;\n\x0c\x43reateRecord\x12\x14.myapp.CreateRequest\x1a\x15.myapp.CreateResponse\x12\x35\n\nReadRecord\x12\x12.myapp.ReadRequest\x1a\x13.myapp.ReadResponse\x12;\n\x0cUpdateRecord\x12\x14.myapp.UpdateRequest\x1a\x15.myapp.UpdateResponse\x12;\n\x0c\x44\x65leteRecord\x12\x14.myapp.DeleteRequest\x1a\x15.myapp.DeleteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUEST._serialized_start=24
  _CREATEREQUEST._serialized_end=90
  _CREATERESPONSE._serialized_start=92
  _CREATERESPONSE._serialized_end=125
  _READREQUEST._serialized_start=127
  _READREQUEST._serialized_end=159
  _READRESPONSE._serialized_start=161
  _READRESPONSE._serialized_end=189
  _UPDATEREQUEST._serialized_start=191
  _UPDATEREQUEST._serialized_end=276
  _UPDATERESPONSE._serialized_start=278
  _UPDATERESPONSE._serialized_end=311
  _DELETEREQUEST._serialized_start=313
  _DELETEREQUEST._serialized_end=347
  _DELETERESPONSE._serialized_start=349
  _DELETERESPONSE._serialized_end=382
  _DATABASESERVICE._serialized_start=385
  _DATABASESERVICE._serialized_end=640
# @@protoc_insertion_point(module_scope)
