# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_pb2.users import users_pb2 as proto__pb2_dot_users__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRecordUsers = channel.unary_unary(
                '/UserService/CreateRecordUsers',
                request_serializer=proto__pb2_dot_users__pb2.CreateRequestUsers.SerializeToString,
                response_deserializer=proto__pb2_dot_users__pb2.CreateResponseUsers.FromString,
                )
        self.ReadRecordUsers = channel.unary_unary(
                '/UserService/ReadRecordUsers',
                request_serializer=proto__pb2_dot_users__pb2.ReadRequestUsers.SerializeToString,
                response_deserializer=proto__pb2_dot_users__pb2.ReadResponseUsers.FromString,
                )
        self.UpdateRecordUsers = channel.unary_unary(
                '/UserService/UpdateRecordUsers',
                request_serializer=proto__pb2_dot_users__pb2.UpdateRequestUsers.SerializeToString,
                response_deserializer=proto__pb2_dot_users__pb2.UpdateResponseUsers.FromString,
                )
        self.DeleteRecordUsers = channel.unary_unary(
                '/UserService/DeleteRecordUsers',
                request_serializer=proto__pb2_dot_users__pb2.DeleteRequestUsers.SerializeToString,
                response_deserializer=proto__pb2_dot_users__pb2.DeleteResponseUsers.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRecordUsers(self, request, context):
        """USERS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRecordUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecordUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecordUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRecordUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecordUsers,
                    request_deserializer=proto__pb2_dot_users__pb2.CreateRequestUsers.FromString,
                    response_serializer=proto__pb2_dot_users__pb2.CreateResponseUsers.SerializeToString,
            ),
            'ReadRecordUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRecordUsers,
                    request_deserializer=proto__pb2_dot_users__pb2.ReadRequestUsers.FromString,
                    response_serializer=proto__pb2_dot_users__pb2.ReadResponseUsers.SerializeToString,
            ),
            'UpdateRecordUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecordUsers,
                    request_deserializer=proto__pb2_dot_users__pb2.UpdateRequestUsers.FromString,
                    response_serializer=proto__pb2_dot_users__pb2.UpdateResponseUsers.SerializeToString,
            ),
            'DeleteRecordUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecordUsers,
                    request_deserializer=proto__pb2_dot_users__pb2.DeleteRequestUsers.FromString,
                    response_serializer=proto__pb2_dot_users__pb2.DeleteResponseUsers.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRecordUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/CreateRecordUsers',
            proto__pb2_dot_users__pb2.CreateRequestUsers.SerializeToString,
            proto__pb2_dot_users__pb2.CreateResponseUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRecordUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/ReadRecordUsers',
            proto__pb2_dot_users__pb2.ReadRequestUsers.SerializeToString,
            proto__pb2_dot_users__pb2.ReadResponseUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRecordUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/UpdateRecordUsers',
            proto__pb2_dot_users__pb2.UpdateRequestUsers.SerializeToString,
            proto__pb2_dot_users__pb2.UpdateResponseUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecordUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserService/DeleteRecordUsers',
            proto__pb2_dot_users__pb2.DeleteRequestUsers.SerializeToString,
            proto__pb2_dot_users__pb2.DeleteResponseUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
