# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_pb2.project_members import project_members_pb2 as proto__pb2_dot_project__members_dot_project__members__pb2


class ProjectMembersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRecordProjectMembers = channel.unary_unary(
                '/ProjectMembersService/CreateRecordProjectMembers',
                request_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersResponse.FromString,
                )
        self.ReadRecordProjectMembers = channel.unary_unary(
                '/ProjectMembersService/ReadRecordProjectMembers',
                request_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersResponse.FromString,
                )
        self.UpdateRecordProjectMembers = channel.unary_unary(
                '/ProjectMembersService/UpdateRecordProjectMembers',
                request_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersResponse.FromString,
                )
        self.DeleteRecordProjectMembers = channel.unary_unary(
                '/ProjectMembersService/DeleteRecordProjectMembers',
                request_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersResponse.FromString,
                )


class ProjectMembersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRecordProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRecordProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecordProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecordProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectMembersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRecordProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecordProjectMembers,
                    request_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersRequest.FromString,
                    response_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersResponse.SerializeToString,
            ),
            'ReadRecordProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRecordProjectMembers,
                    request_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersRequest.FromString,
                    response_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersResponse.SerializeToString,
            ),
            'UpdateRecordProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecordProjectMembers,
                    request_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersRequest.FromString,
                    response_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersResponse.SerializeToString,
            ),
            'DeleteRecordProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecordProjectMembers,
                    request_deserializer=proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersRequest.FromString,
                    response_serializer=proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProjectMembersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectMembersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRecordProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectMembersService/CreateRecordProjectMembers',
            proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersRequest.SerializeToString,
            proto__pb2_dot_project__members_dot_project__members__pb2.CreateProjectMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRecordProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectMembersService/ReadRecordProjectMembers',
            proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersRequest.SerializeToString,
            proto__pb2_dot_project__members_dot_project__members__pb2.ReadProjectMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRecordProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectMembersService/UpdateRecordProjectMembers',
            proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersRequest.SerializeToString,
            proto__pb2_dot_project__members_dot_project__members__pb2.UpdateProjectMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecordProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectMembersService/DeleteRecordProjectMembers',
            proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersRequest.SerializeToString,
            proto__pb2_dot_project__members_dot_project__members__pb2.DeleteProjectMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
