# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_pb2.files import files_pb2 as proto__pb2_dot_files_dot_files__pb2


class FilesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFilesRecord = channel.unary_unary(
                '/FilesService/CreateFilesRecord',
                request_serializer=proto__pb2_dot_files_dot_files__pb2.CreateFilesRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_files_dot_files__pb2.CreateFilesResponse.FromString,
                )
        self.ReadFilesRecord = channel.unary_unary(
                '/FilesService/ReadFilesRecord',
                request_serializer=proto__pb2_dot_files_dot_files__pb2.ReadFilesRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_files_dot_files__pb2.ReadFilesResponse.FromString,
                )
        self.UpdateFilesRecord = channel.unary_unary(
                '/FilesService/UpdateFilesRecord',
                request_serializer=proto__pb2_dot_files_dot_files__pb2.UpdateFilesRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_files_dot_files__pb2.UpdateFilesResponse.FromString,
                )
        self.DeleteFilesRecord = channel.unary_unary(
                '/FilesService/DeleteFilesRecord',
                request_serializer=proto__pb2_dot_files_dot_files__pb2.DeleteFilesRequest.SerializeToString,
                response_deserializer=proto__pb2_dot_files_dot_files__pb2.DeleteFilesResponse.FromString,
                )


class FilesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFilesRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFilesRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFilesRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFilesRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFilesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFilesRecord,
                    request_deserializer=proto__pb2_dot_files_dot_files__pb2.CreateFilesRequest.FromString,
                    response_serializer=proto__pb2_dot_files_dot_files__pb2.CreateFilesResponse.SerializeToString,
            ),
            'ReadFilesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFilesRecord,
                    request_deserializer=proto__pb2_dot_files_dot_files__pb2.ReadFilesRequest.FromString,
                    response_serializer=proto__pb2_dot_files_dot_files__pb2.ReadFilesResponse.SerializeToString,
            ),
            'UpdateFilesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFilesRecord,
                    request_deserializer=proto__pb2_dot_files_dot_files__pb2.UpdateFilesRequest.FromString,
                    response_serializer=proto__pb2_dot_files_dot_files__pb2.UpdateFilesResponse.SerializeToString,
            ),
            'DeleteFilesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFilesRecord,
                    request_deserializer=proto__pb2_dot_files_dot_files__pb2.DeleteFilesRequest.FromString,
                    response_serializer=proto__pb2_dot_files_dot_files__pb2.DeleteFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FilesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FilesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFilesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FilesService/CreateFilesRecord',
            proto__pb2_dot_files_dot_files__pb2.CreateFilesRequest.SerializeToString,
            proto__pb2_dot_files_dot_files__pb2.CreateFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFilesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FilesService/ReadFilesRecord',
            proto__pb2_dot_files_dot_files__pb2.ReadFilesRequest.SerializeToString,
            proto__pb2_dot_files_dot_files__pb2.ReadFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFilesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FilesService/UpdateFilesRecord',
            proto__pb2_dot_files_dot_files__pb2.UpdateFilesRequest.SerializeToString,
            proto__pb2_dot_files_dot_files__pb2.UpdateFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFilesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FilesService/DeleteFilesRecord',
            proto__pb2_dot_files_dot_files__pb2.DeleteFilesRequest.SerializeToString,
            proto__pb2_dot_files_dot_files__pb2.DeleteFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
