# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_pb2/projects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto_pb2/projects.proto\x12\x0bgeoresearch\"J\n\x15\x43reateRequestProjects\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\":\n\x16\x43reateResponseProjects\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"T\n\x13ReadRequestProjects\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x8a\x01\n\x14ReadResponseProjects\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07success\x18\x06 \x01(\x08\x12\x0f\n\x07message\x18\x07 \x01(\t\"V\n\x15UpdateRequestProjects\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\":\n\x16UpdateResponseProjects\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\x15\x44\x65leteRequestProjects\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\":\n\x16\x44\x65leteResponseProjects\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8f\x03\n\x0fProjectsService\x12_\n\x14\x43reateRecordProjects\x12\".georesearch.CreateRequestProjects\x1a#.georesearch.CreateResponseProjects\x12Y\n\x12ReadRecordProjects\x12 .georesearch.ReadRequestProjects\x1a!.georesearch.ReadResponseProjects\x12_\n\x14UpdateRecordProjects\x12\".georesearch.UpdateRequestProjects\x1a#.georesearch.UpdateResponseProjects\x12_\n\x14\x44\x65leteRecordProjects\x12\".georesearch.DeleteRequestProjects\x1a#.georesearch.DeleteResponseProjectsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2.projects_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUESTPROJECTS._serialized_start=41
  _CREATEREQUESTPROJECTS._serialized_end=115
  _CREATERESPONSEPROJECTS._serialized_start=117
  _CREATERESPONSEPROJECTS._serialized_end=175
  _READREQUESTPROJECTS._serialized_start=177
  _READREQUESTPROJECTS._serialized_end=261
  _READRESPONSEPROJECTS._serialized_start=264
  _READRESPONSEPROJECTS._serialized_end=402
  _UPDATEREQUESTPROJECTS._serialized_start=404
  _UPDATEREQUESTPROJECTS._serialized_end=490
  _UPDATERESPONSEPROJECTS._serialized_start=492
  _UPDATERESPONSEPROJECTS._serialized_end=550
  _DELETEREQUESTPROJECTS._serialized_start=552
  _DELETEREQUESTPROJECTS._serialized_end=638
  _DELETERESPONSEPROJECTS._serialized_start=640
  _DELETERESPONSEPROJECTS._serialized_end=698
  _PROJECTSSERVICE._serialized_start=701
  _PROJECTSSERVICE._serialized_end=1100
# @@protoc_insertion_point(module_scope)
