# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_pb2/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_pb2/service.proto\"B\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"2\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"q\n\x0cReadResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07success\x18\x06 \x01(\x08\"N\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcf\x01\n\x0f\x44\x61tabaseService\x12/\n\x0c\x43reateRecord\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\x12)\n\nReadRecord\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12/\n\x0cUpdateRecord\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12/\n\x0c\x44\x65leteRecord\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEREQUEST._serialized_start=27
  _CREATEREQUEST._serialized_end=93
  _CREATERESPONSE._serialized_start=95
  _CREATERESPONSE._serialized_end=145
  _READREQUEST._serialized_start=147
  _READREQUEST._serialized_end=172
  _READRESPONSE._serialized_start=174
  _READRESPONSE._serialized_end=287
  _UPDATEREQUEST._serialized_start=289
  _UPDATEREQUEST._serialized_end=367
  _UPDATERESPONSE._serialized_start=369
  _UPDATERESPONSE._serialized_end=419
  _DELETEREQUEST._serialized_start=421
  _DELETEREQUEST._serialized_end=448
  _DELETERESPONSE._serialized_start=450
  _DELETERESPONSE._serialized_end=500
  _DATABASESERVICE._serialized_start=503
  _DATABASESERVICE._serialized_end=710
# @@protoc_insertion_point(module_scope)
